swagger: '2.0'
info:
  title: おみくじ
  version: '1.0'
  contact:
    name: 古河和樹
  description: おみくじ API
host: 'localhost:3000'
tags:
  - name: おみくじ
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  '/omikuji/{omikuji_id}':
    get:
      summary: おみくじ結果を取得する
      tags: []
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              options:
                type: array
                items:
                  type: string
              resultIndex:
                type: integer
                minimum: 0
            required:
              - options
              - resultIndex
      operationId: get-omikuji
      description: ''
    parameters:
      - type: string
        name: omikuji_id
        in: path
        required: true
definitions: {}
